### ISSUE TITLE
Swipe to scroll resets after releasing finger on IOS

### ISSUE THREAD

**Issue by jon-stayntouch** [iamvijaydev/augment-native-scroll#2]

**Comment by iamvijaydev** [comment]
I have fixed and finalized the flavor that can work on both touch and non-touch devices. [Synchronous Scroll Swipe](https://iamvijaydev.github.io/augment-native-scroll/#/synchronous-scroll-swipe)

For more info, please check the latest (v0.6.0) [README](https://github.com/iamvijaydev/augment-native-scroll#augment-native-scroll)

Please report back if this happens with the final flavor

**Comment by iamvijaydev** [comment]
Hi @jon-stayntouch  

Thank you for your valuable review. The kinetic engine has been re-written. Older experiments has been close. Please check the new [demo here](https://iamvijaydev.github.io/augment-native-scroll/#/synchronous-scroll-swipe)
