### ISSUE TITLE
Selectable content

### ISSUE THREAD

**Issue by sstajduhar** [iamvijaydev/augment-native-scroll#4]
I'm worried about this line since we should be able to select content - https://github.com/iamvijaydev/augment-native-scroll/blob/master/src/scss/styles.scss#L19

Removing this would disable swipe on non touch devices, but what will happen on touch devices?

**Comment by iamvijaydev** [comment]
Hi @sstajduhar, 

Thank you for your valuable review.  That style is for demo only.

The kinetic engine has been re-written. Older experiments has been close. Please check the new [demo here](https://iamvijaydev.github.io/augment-native-scroll/#/synchronous-scroll-swipe)
