### ISSUE TITLE
Swipe to scroll locks focus on Safari, Mac OS

### ISSUE THREAD

**Issue by sstajduhar** [iamvijaydev/augment-native-scroll#5]
For both Swipe to Scroll and Synchronous Scroll Swipe I get the same effect - when I click to swipe screen keeps on moving after I've released the mouse button and clicked several times on the screen.

**Comment by iamvijaydev** [comment]
Hi @sstajduhar, 

Thank you for your valuable review. The kinetic engine has been re-written. Older experiments has been close. Please check the new [demo here](https://iamvijaydev.github.io/augment-native-scroll/#/synchronous-scroll-swipe)
